[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

build_flags =
  # exFAT filesystem support (requires LFN)
  -D CONFIG_FATFS_LFN_HEAP=1
  -D FF_FS_EXFAT=1

  # VBA emulator defines
  -D LOAD_FROM_MEMORY=1
  -D HAVE_HLE_BIOS=1
  -D USE_TWEAKS=1
  -D USE_FRAME_SKIP=0
  -D THREADED_RENDERER=0
  -D USE_MOTION_SENSOR=0
  -D USE_CHEATS=0
  -D USE_SWITICKS=0
  -D FRONTEND_SUPPORTS_RGB565=1
  -D INLINE=inline
